const ROLES_DATA = [
  // ===== 市民陣営 =====
  { name: '市民', team: 'village', rarity: '基本', ability: 'なし',
    description: '特殊能力を持たない一般市民。議論と投票で人狼を見つけ出す。',
    strategy: '発言の矛盾や行動パターンからスキルで人狼を見抜く。寡黙にならず積極的に議論に参加することが大切。',
    compatibility: { good: ['占い師', '霊能者'], bad: ['人狼'], tips: '特殊能力がないため推理力が勝負。' },
    nightAction: false, icon: '\u{1F464}', color: '#7ee787' },
  { name: '占い師', team: 'village', rarity: '基本', ability: '占い',
    description: '毎晩一人を選んで占い、人狼かどうかを知ることができる。村の最重要役職。',
    strategy: '初日に即COし、毎日占い結果を報告する。グレーを詰める占いが基本。対抗が出た場合はロラ（ローラー）か真偽判定を行う。',
    compatibility: { good: ['霊能者', '狩人', '賢者'], bad: ['人狼', '狂人', '妖狐'], tips: '狩人の護衛が生命線。霊能者との情報照合が重要。' },
    nightAction: true, icon: '\u{1F52E}', color: '#a78bfa' },
  { name: '霊能者', team: 'village', rarity: '基本', ability: '霊能',
    description: '処刑された人が人狼だったかどうかを知ることができる。',
    strategy: '占い師の真偽判定に重要。COタイミングは占い師と同日か、対抗が出た場合に。',
    compatibility: { good: ['占い師', '狩人'], bad: ['人狼', '狂人'], tips: '占い師の結果と照合して真偽を判断する。' },
    nightAction: false, icon: '\u{1F47B}', color: '#79c0ff' },
  { name: '狩人', team: 'village', rarity: '基本', ability: '護衛',
    description: '毎晩一人を護衛し、人狼の襲撃から守ることができる。連続護衛不可のルールもある。',
    strategy: '占い師の護衛が基本。GJ（護衛成功）が出たら状況に応じてCOも視野に。',
    compatibility: { good: ['占い師', '霊能者'], bad: ['人狼', '罠師'], tips: '占い師護衛が基本。GJ時のCO判断が重要。' },
    nightAction: true, icon: '\u{1F3AF}', color: '#3fb950' },
  { name: '猫又', team: 'village', rarity: '特殊', ability: '道連れ',
    description: '処刑された場合、ランダムで一人を道連れにする。人狼に襲撃された場合、襲撃した人狼を道連れにする。',
    strategy: '噛まれた場合は確定で人狼を道連れにできるため、吊られないよう立ち回る。COタイミングが重要。',
    compatibility: { good: ['狩人', '占い師'], bad: ['人狼', '狂人'], tips: '噛まれれば人狼道連れ。吊られると村人巻き込みリスク。' },
    nightAction: false, icon: '\u{1F431}', color: '#f0883e' },
  { name: '双子', team: 'village', rarity: '特殊', ability: '相互認知',
    description: '同じ双子同士でお互いを認知できる。確定白として強力。',
    strategy: '片方がCOし、もう片方が白確認することで強力な白確定が作れる。ただしタイミングに注意。',
    nightAction: false, icon: '\u{1F46F}', color: '#58a6ff' },
  { name: 'パン屋', team: 'village', rarity: '特殊', ability: 'パン配り',
    description: '生存している限り毎朝「パンが届きました」と表示される。死亡すると届かなくなる。',
    strategy: '生存確認役職。パンが届かなくなったら噛まれたことが分かる。白アピールに使える。',
    nightAction: false, icon: '\u{1F35E}', color: '#d2a679' },
  { name: '怪盗', team: 'village', rarity: '特殊', ability: '役職入替',
    description: '初日の夜に他の人と役職を入れ替えることができる。入れ替えた先の役職になる。',
    strategy: '重要役職を引き当てれば強力。自分の元の役職情報も活かして推理を進める。',
    nightAction: true, icon: '\u{1F3AD}', color: '#b392f0' },
  { name: '狼憑き', team: 'village', rarity: '特殊', ability: '占い黒',
    description: '市民陣営だが、占い結果が人狼と出る。そのため人狼に間違えられやすい。',
    strategy: '占いで黒を出されても慌てず弁明する。状況次第で狼憑きCOも選択肢。',
    nightAction: false, icon: '\u{1F43A}', color: '#8b949e' },
  { name: '罠師', team: 'village', rarity: '特殊', ability: '罠設置',
    description: '毎晩一人に罠を仕掛けることができる。罠を仕掛けた人を人狼が襲撃すると人狼が死ぬ。',
    strategy: '狩人と似た役割だが、罠にかかった人狼が死ぬのが最大の違い。噛まれそうな位置に罠を張る。',
    nightAction: true, icon: '\u{1FAA4}', color: '#da3633' },
  { name: '逃亡者', team: 'village', rarity: '特殊', ability: '逃亡',
    description: '毎晩誰かのもとへ逃亡する。逃亡先が人狼だった場合は死亡する。',
    strategy: '白確定の人のもとへ逃亡するのが安全。人狼のもとへ行くと死ぬため、推理力が問われる。',
    nightAction: true, icon: '\u{1F3C3}', color: '#79c0ff' },
  { name: '賢者', team: 'village', rarity: '特殊', ability: '役職占い',
    description: '毎晩一人を選んで、その人の役職を知ることができる。占い師の上位互換。',
    strategy: '占い師と同様にCOして情報を出していく。役職まで分かるので対抗の真偽判定に強い。',
    nightAction: true, icon: '\u{1F4D6}', color: '#a5d6ff' },
  { name: '市長', team: 'village', rarity: '特殊', ability: '票2倍',
    description: '投票時の票が2票分としてカウントされる。',
    strategy: '票の影響力が大きいため、正確な推理が重要。COのタイミングは終盤が効果的。',
    nightAction: false, icon: '\u{1F3DB}', color: '#7ee787' },
  { name: '占い師の弟子', team: 'village', rarity: '特殊', ability: '占い継承',
    description: '占い師が死亡した場合、占い師の能力を引き継ぐ。',
    strategy: '占い師が死ぬまでは能力なし。占い師死亡後にCOして占い結果を出していく。',
    nightAction: false, icon: '\u{2728}', color: '#d2a8ff' },
  { name: '赤ずきん', team: 'village', rarity: '特殊', ability: '襲撃耐性（狩人生存時）',
    description: '狩人が生存している間は、人狼に襲撃されても死なない。',
    strategy: '狩人の生存が鍵。狩人が死亡すると普通に襲撃されるので注意。',
    nightAction: false, icon: '\u{1F9E3}', color: '#f85149' },
  { name: '貴族', team: 'village', rarity: '特殊', ability: '身代わり',
    description: '人狼に襲撃された場合、奴隷が身代わりに死ぬ。',
    strategy: '奴隷とセットの役職。奴隷が生存している限り襲撃されても死なない。',
    nightAction: false, icon: '\u{1F451}', color: '#f0c000' },
  { name: '奴隷', team: 'village', rarity: '特殊', ability: '身代わり死',
    description: '貴族が襲撃された場合、代わりに死亡する。',
    strategy: '貴族を守るために潜伏が基本。自分が死んでも貴族が生き残れば村に貢献。',
    nightAction: false, icon: '\u{26D3}', color: '#8b949e' },
  { name: '聖職者', team: 'village', rarity: '特殊', ability: '1回護衛',
    description: '一度だけ人狼の襲撃を防ぐことができる。自動発動。',
    strategy: '自動で1回だけ襲撃を防ぐ。潜伏しつつ、生存を活かして推理に貢献。',
    nightAction: false, icon: '\u{271D}', color: '#f0e68c' },
  { name: '神父', team: 'village', rarity: '特殊', ability: '祈り',
    description: '毎晩一人を選んで祈りを捧げることができる。祈られた人は一度だけ人狼の襲撃を耐えることができる。',
    strategy: '重要役職を守るために祈りを捧げる。狩人と役割が似ているが、護衛ではなく耐性付与なので使い分けが重要。',
    quote: '2・・・3\n5・・・7・・・\n11・・・13・・・17\n・・・・・19\n落ちつくんだ・・・\n『素数』を数えて\n落ちつくんだ・・・\n『素数』は\n1と自分の数でしか\n割ることのできない\n孤独な数字・・・・・\nわたしに\n勇気を与えてくれる',
    nightAction: true, icon: '\u{26EA}', color: '#f0e68c' },
  { name: '巫女', team: 'village', rarity: '特殊', ability: '呪い判定',
    description: '処刑された人が人狼陣営かどうかを知ることができる。霊能者と似た能力。',
    strategy: '霊能者と同様に処刑者の判定を出す。COタイミングが重要。',
    nightAction: false, icon: '\u{26E9}', color: '#ff79c6' },
  { name: '暗殺者', team: 'village', rarity: '特殊', ability: '暗殺',
    description: 'ゲーム中一度だけ、指定した人を暗殺できる。',
    strategy: '確定人狼や確定黒位置に使う。使いどころを誤ると村に不利になるため慎重に。',
    nightAction: true, icon: '\u{1F5E1}', color: '#6e7681' },
  { name: '呪われし者', team: 'village', rarity: '特殊', ability: '襲撃で転化',
    description: '人狼に襲撃されると死なずに人狼になる。占い結果は白。',
    strategy: '襲撃されると人狼に転化するため、村にとって危険な存在にもなり得る。',
    nightAction: false, icon: '\u{1F319}', color: '#8957e5' },
  { name: '独裁者', team: 'village', rarity: '特殊', ability: '即処刑',
    description: 'ゲーム中一度だけ、投票時に独裁を発動し指定した人を即処刑できる。',
    strategy: '確実に人狼と分かっている人に使う。誤爆すると村が大きく不利に。',
    nightAction: false, icon: '\u{1F4E2}', color: '#da3633' },
  { name: 'わら人形', team: 'village', rarity: '特殊', ability: '処刑道連れ',
    description: '処刑された場合、任意の一人を道連れにできる。',
    strategy: '吊られそうな時に道連れ先を決める。確定黒を道連れにできれば大きい。',
    nightAction: false, icon: '\u{1F9F8}', color: '#d2a679' },
  { name: '女王', team: 'village', rarity: '特殊', ability: '市民認知',
    description: '市民陣営全員が女王を認知している。女王が死亡すると市民陣営は敗北。',
    strategy: '絶対に死んではいけない役職。市民陣営全員で守る必要がある。',
    nightAction: false, icon: '\u{1F478}', color: '#f0c000' },
  { name: '病人', team: 'village', rarity: '特殊', ability: '襲撃時無力化',
    description: '人狼に襲撃された場合、翌日その人狼は能力を使えなくなる。',
    strategy: '噛まれることで人狼を弱体化できる。潜伏して噛まれるのを待つ。',
    nightAction: false, icon: '\u{1F912}', color: '#3fb950' },
  { name: '魔女', team: 'village', rarity: '特殊', ability: '蘇生/毒殺',
    description: '一度だけ蘇生の薬と毒殺の薬をそれぞれ使える。',
    strategy: '蘇生は重要役職に、毒殺は確定人狼に使う。両方1回ずつしか使えないので慎重に。',
    nightAction: true, icon: '\u{1F9D9}', color: '#a78bfa' },
  { name: '番犬', team: 'village', rarity: '特殊', ability: '初日護衛指定',
    description: '初日の夜に一人を選び、その人が人狼なら自分が死亡。市民なら毎晩その人を護衛。',
    strategy: '初日に白い人を選ぶのが重要。成功すれば確定護衛先ができるが、失敗すると即死。',
    nightAction: true, icon: '\u{1F415}', color: '#f0883e' },
  { name: '偽占い師', team: 'village', rarity: '特殊', ability: '偽占い',
    description: '占い師だと思っているが、占い結果がランダムで出る。本人は自分が偽物だと知らない。',
    strategy: '自分では占い師だと思って行動する。結果が不正確なので、他の情報と突き合わせが重要。',
    nightAction: true, icon: '\u{2753}', color: '#8b949e' },
  { name: '長老', team: 'village', rarity: '特殊', ability: '2回耐性',
    description: '人狼の襲撃を一度だけ耐えることができる。2回目の襲撃で死亡する。',
    strategy: '噛まれても1回は生存できるため、潜伏して情報を集めやすい。ただし処刑では1回で死ぬ。',
    nightAction: false, icon: '\u{1F9D3}', color: '#8b949e' },
  { name: '生霊', team: 'village', rarity: '特殊', ability: '役職コピー',
    description: '初日の夜に一人を選び、その人が死亡した時にその人の役職をコピーする。',
    strategy: '重要役職をコピー対象にすると、その人の死後に能力を引き継げる。',
    nightAction: true, icon: '\u{1F47B}', color: '#b392f0' },
  { name: '医者', team: 'village', rarity: '特殊', ability: '蘇生',
    description: '毎晩一人を選び、その人が死亡した場合に一定確率で蘇生させることができる。',
    strategy: '重要役職が死亡した場合の保険。蘇生成功率は低いが、成功すれば非常に強力。',
    nightAction: true, icon: '\u{1FA7A}', color: '#3fb950' },
  { name: '人狼キラー', team: 'village', rarity: '特殊', ability: '襲撃返し',
    description: '人狼に襲撃された時、襲撃してきた人狼を殺すことができる。自身も死亡する。',
    strategy: '噛まれた時に人狼を道連れにできる。猫又と似ているが確定で襲撃者を殺す。',
    nightAction: false, icon: '\u{2694}', color: '#f85149' },

  // ===== 人狼陣営 =====
  { name: '人狼', team: 'werewolf', rarity: '基本', ability: '襲撃',
    description: '毎晩一人を襲撃できる。人狼同士は互いを認知でき、夜に会話できる。',
    strategy: '市民のふりをして議論をかく乱する。占い師騙りや潜伏など戦術は多彩。仲間との連携が重要。',
    compatibility: { good: ['狂人', '狂信者', 'ささやく狂人'], bad: ['占い師', '狩人', '賢者'], tips: '仲間との連携が重要。占い師の排除が最優先。' },
    nightAction: true, icon: '\u{1F47A}', color: '#f85149' },
  { name: '狂人', team: 'werewolf', rarity: '基本', ability: 'なし（占い白）',
    description: '人狼陣営だが人狼ではないため、占い結果は白（市民）と出る。',
    strategy: '占い師や霊能者を騙って人狼を援護する。人狼が誰かは分からないので、推理して合わせる。',
    compatibility: { good: ['人狼'], bad: ['霊能者', '占い師'], tips: '占い騙りで人狼をサポート。PPを狙う。' },
    nightAction: false, icon: '\u{1F608}', color: '#da3633' },
  { name: '狂信者', team: 'werewolf', rarity: '特殊', ability: '人狼認知',
    description: '狂人の上位互換。人狼が誰か知った状態でゲームが始まる。占い結果は白。',
    strategy: '人狼を知っているので、的確に援護できる。騙り役として非常に強力。',
    nightAction: false, icon: '\u{1F631}', color: '#f47067' },
  { name: 'ささやく狂人', team: 'werewolf', rarity: '特殊', ability: '人狼チャット参加',
    description: '人狼のチャットに参加でき、人狼と会話ができる狂人。',
    strategy: '人狼と直接連携できるため、騙りの整合性を取りやすい。最も強力な狂人系。',
    nightAction: false, icon: '\u{1F5E3}', color: '#ff7b72' },
  { name: '大狼', team: 'werewolf', rarity: '特殊', ability: '占い白',
    description: '人狼だが、占い結果が白（市民）と出る。',
    strategy: '占いで白が出るため、占い師の結果を混乱させられる。潜伏が非常に強力。',
    nightAction: true, icon: '\u{1F43B}', color: '#da3633' },
  { name: 'サイコ', team: 'werewolf', rarity: '特殊', ability: '護衛先襲撃',
    description: '狩人に護衛された人を襲撃しても、護衛を無視して襲撃が成功する。',
    strategy: '狩人の護衛を無効化できるため、確定護衛先でも安心して襲撃できる。',
    quote: '2・・・3\n5・・・7・・・\n11・・・13・・・17\n・・・・・19\n落ちつくんだ・・・\n『素数』を数えて\n落ちつくんだ・・・\n『素数』は\n1と自分の数でしか\n割ることのできない\n孤独な数字・・・・・\nわたしに\n勇気を与えてくれる',
    nightAction: true, icon: '\u{1F525}', color: '#f85149' },
  { name: '妖術師', team: 'werewolf', rarity: '特殊', ability: '占い（人狼側）',
    description: '人狼陣営の占い師。毎晩一人を占い、役職を知ることができる。',
    strategy: '偽占い師として振る舞いつつ、村の役職を把握して人狼に情報を伝える。',
    nightAction: true, icon: '\u{1F9D9}', color: '#f47067' },
  { name: '狼少年', team: 'werewolf', rarity: '特殊', ability: '霊能操作',
    description: '処刑された場合、霊能者の結果を白に変える。',
    strategy: '吊られても霊能結果を白にできるため、人狼の吊りミスを隠蔽できる。',
    nightAction: false, icon: '\u{1F466}', color: '#ff7b72' },
  { name: '黒猫', team: 'werewolf', rarity: '特殊', ability: '処刑道連れ',
    description: '処刑された場合、ランダムで村人陣営から一人を道連れにする。',
    strategy: '積極的に吊られにいくことで村を減らせる。猫又COして吊りを誘う戦術も。',
    nightAction: false, icon: '\u{1F408}', color: '#6e7681' },
  { name: '賢狼', team: 'werewolf', rarity: '特殊', ability: '役職看破',
    description: '襲撃した人の役職を知ることができる人狼。',
    strategy: '噛んだ相手の役職がわかるため、情報アドバンテージが大きい。',
    nightAction: true, icon: '\u{1F9D0}', color: '#da3633' },
  { name: '饒舌な人狼', team: 'werewolf', rarity: '特殊', ability: 'ワード強制',
    description: '毎日、指定されたワードを発言に含めなければならない人狼。含めないと死亡。',
    strategy: '指定ワードを自然に会話に組み込む。不自然な発言は疑われるので注意。',
    nightAction: true, icon: '\u{1F4AC}', color: '#f47067' },
  { name: '蘇る人狼', team: 'werewolf', rarity: '特殊', ability: '自己蘇生',
    description: '一度だけ死亡後に蘇生できる人狼。',
    strategy: '1回死んでも復活できるため、積極的に騙りに出ることも可能。',
    nightAction: true, icon: '\u{1F480}', color: '#da3633' },
  { name: '能ある人狼', team: 'werewolf', rarity: '特殊', ability: '能力隠し',
    description: '占い師に占われた際、占い結果を白にすることができる人狼。',
    strategy: '占い師に対して強い。白結果を出させて潜伏を維持できる。',
    nightAction: true, icon: '\u{1F3AD}', color: '#f85149' },
  { name: '強欲な人狼', team: 'werewolf', rarity: '特殊', ability: '2人襲撃',
    description: '一度だけ、一晩に二人を襲撃することができる人狼。',
    strategy: '終盤の詰みで使ったり、重要役職を一気に2人噛むなど、タイミングが勝負の鍵。',
    nightAction: true, icon: '\u{1F4B0}', color: '#da3633' },
  { name: '悪徳政治家', team: 'werewolf', rarity: '特殊', ability: '票操作',
    description: '投票数を操作することができる人狼陣営の役職。処刑投票で有利に立ち回れる。',
    strategy: '投票操作で村の処刑先をコントロールする。重要な局面で票を操作して村を混乱させる。',
    nightAction: false, icon: '\u{1F4BC}', color: '#f47067' },

  // ===== 妖狐陣営 =====
  { name: '妖狐', team: 'fox', rarity: '特殊', ability: '襲撃耐性',
    description: '人狼に襲撃されても死なない。ただし占い師に占われると死ぬ（呪殺）。勝利条件は生存。',
    strategy: '占われないように目立たず立ち回る。村でも狼でもない第三勢力として、漁夫の利を狙う。',
    compatibility: { good: [], bad: ['占い師', '賢者'], tips: '占われると呪殺される。両陣営をうまく利用して生存する。' },
    nightAction: false, icon: '\u{1F98A}', color: '#d29922' },
  { name: '子狐', team: 'fox', rarity: '特殊', ability: '曖昧占い',
    description: '一定確率で占いの結果がわかる（失敗することもある）。占い師に占われると死ぬ。',
    strategy: '不確実だが占い能力を活かして狐陣営の生存を助ける。',
    nightAction: true, icon: '\u{1F43E}', color: '#e3b341' },
  { name: '背徳者', team: 'fox', rarity: '特殊', ability: '狐認知',
    description: '妖狐が誰かを知った状態でゲーム開始。妖狐が全滅すると後追い死する。',
    strategy: '妖狐の援護役。狂人のように振る舞いつつ、妖狐を守る立ち回りが重要。',
    nightAction: false, icon: '\u{1F47D}', color: '#d29922' },

  // ===== 恋人陣営 =====
  { name: '恋人', team: 'lovers', rarity: '特殊', ability: '相互認知・後追い',
    description: '恋人同士はお互いを認知。片方が死ぬともう片方も後追い死する。恋人だけで生存すれば勝利。',
    strategy: '目立たず生存することが最優先。お互いを庇いすぎるとバレるので注意。',
    nightAction: false, icon: '\u{1F495}', color: '#db7ff7' },

  // ===== その他陣営 =====
  { name: 'ゾンビ', team: 'other', rarity: '特殊', ability: '感染',
    description: '襲撃されると死なずにゾンビになる。ゾンビは毎晩一人を感染させ、感染者がゾンビ陣営になる。',
    strategy: '感染を広げて陣営を拡大する。終盤にゾンビ陣営が多数派になれば勝利。',
    nightAction: true, icon: '\u{1F9DF}', color: '#3fb950' },
  { name: 'サンタ', team: 'other', rarity: '特殊', ability: 'プレゼント',
    description: '全員にプレゼントを配りきると勝利。毎晩一人にプレゼントを渡す。',
    strategy: '全員に配りきる前に死なないことが重要。目立たず生存を優先。',
    nightAction: true, icon: '\u{1F385}', color: '#f85149' },
  { name: 'てるてる坊主', team: 'other', rarity: '特殊', ability: '処刑勝利',
    description: '処刑されると勝利する。ただし初日処刑では勝利にならない。',
    strategy: '吊られそうな立ち回りをしつつ、初日以外で処刑される。わざと怪しく振る舞う。',
    nightAction: false, icon: '\u{1F47B}', color: '#79c0ff' },
  { name: 'ぶた男', team: 'other', rarity: '特殊', ability: '襲撃勝利',
    description: '人狼に襲撃されると勝利する。',
    strategy: '噛まれるように仕向ける。重要役職っぽく振る舞い、噛み先に選ばれる。',
    nightAction: false, icon: '\u{1F437}', color: '#f0883e' },
  { name: '殉教者', team: 'other', rarity: '特殊', ability: '後追い勝利',
    description: '自分が好きな人を選び、その人が死亡した時に後追い死して勝利。',
    strategy: '選んだ相手が死ぬように仕向ける、または自然と死ぬのを待つ。',
    nightAction: false, icon: '\u{1F4AB}', color: '#a78bfa' },
  { name: 'コウモリ男', team: 'other', rarity: '特殊', ability: '生存勝利',
    description: 'どの陣営にも属さず、ゲーム終了時に生存していれば勝利。',
    strategy: '全陣営から敵視されないよう立ち回る。バランサーとして振る舞うのが有効。',
    nightAction: false, icon: '\u{1F987}', color: '#6e7681' },
  { name: '指導者', team: 'other', rarity: '特殊', ability: '陣営指揮',
    description: '特定の条件を満たすことで勝利する独立陣営。周囲を味方に引き込む力を持つ。',
    strategy: '独自の勝利条件達成のため、状況を見極めて立ち回る。どの陣営とも協力・敵対し得る。',
    nightAction: true, icon: '\u{1F396}', color: '#f0c000' },
  { name: '銀色の影', team: 'other', rarity: 'V3', ability: '潜伏',
    description: '独立陣営の役職。特殊な勝利条件を持ち、どの陣営にも属さず独自に生存を目指す。',
    strategy: '誰にも正体を悟られないよう潜伏し、独自の勝利条件を達成しよう。',
    nightAction: false, icon: '\u{1FA9F}', color: '#c0c0c0' },

  // ===== V3 新役職（市民陣営） =====
  { name: '聖騎士', team: 'village', rarity: 'V3', ability: '決闘',
    description: '一度だけ、指定した人物と決闘を行い、相手が人狼陣営であれば処刑する。相手が市民陣営だった場合は自分が死亡する。',
    strategy: '確実に人狼陣営と分かっている相手に使う。推理が外れると自滅するため、情報が揃ってから使おう。',
    nightAction: true, icon: '\u{1F6E1}', color: '#7ee787' },
  { name: '墓場の司祭', team: 'village', rarity: 'V3', ability: '墓場投票',
    description: '人狼の襲撃で死亡した場合、墓場から投票に参加できる。処刑や道連れで死亡した場合は投票不可。',
    strategy: '噛まれた後も村に貢献できる。生前の推理をしっかり行い、墓場からの投票で最後の一押しを。',
    nightAction: false, icon: '\u{26B0}', color: '#79c0ff' },
  { name: '魔法少女', team: 'village', rarity: 'V3', ability: '三種の魔法',
    description: '「占い」「霊能」「護衛」の能力をそれぞれ一度ずつ使用できる万能型の役職。',
    strategy: '3つの能力を適切なタイミングで使い分ける。序盤は占い、中盤は護衛、終盤は霊能など状況判断が重要。',
    nightAction: true, icon: '\u{1FA84}', color: '#a78bfa' },
  { name: 'チキン', team: 'village', rarity: 'V3', ability: '逃走',
    description: '投票で最多票を得た場合、処刑を回避して翌日に持ち越すことがある。',
    strategy: '処刑回避能力があるが確実ではない。グレランで吊り位置にいても生き延びられることがある。',
    nightAction: false, icon: '\u{1F414}', color: '#7ee787' },
  { name: '偽女王', team: 'village', rarity: 'V3', ability: '偽りの女王',
    description: '自分を女王だと思い込んでいる市民。役職欄には「女王」と表示されるが偽物のため、死亡しても後追い死は発生しない。',
    strategy: '自分が偽女王とは知らされない。死んでも村に被害がなく、人狼が噛みを躊躇するブラフにもなる。',
    nightAction: false, icon: '\u{1F478}', color: '#f0c000' },
  { name: 'マッチ売り', team: 'village', rarity: 'V3', ability: 'マッチの幻覚',
    description: '毎夜、指定した相手にマッチを使い、相手が人狼だった場合に幻覚を見せて襲撃を失敗させる。マッチを使い切ると死亡する。',
    strategy: '人狼だと疑わしい相手にマッチを使う。成功すれば襲撃を防げるがマッチ切れで死亡するリスクも。計画的に。',
    nightAction: true, icon: '\u{1F525}', color: '#f0883e' },
  { name: '風来坊', team: 'village', rarity: 'V3', ability: '気配探知',
    description: '毎夜一人を選んで気配を探り、その人が夜に能力を使用したかどうかを知ることができる。',
    strategy: '怪しい相手の夜の行動有無を確認できる。能力未使用の人狼や役職者の真偽判定に有効。',
    nightAction: true, icon: '\u{1F4A8}', color: '#58a6ff' },
  { name: '光の使徒', team: 'village', rarity: 'V3', ability: '役職変化',
    description: '役職確認後、屋敷に含まれていない市民陣営の役職にランダムで変化する。全役職の能力を把握する上級者向け。',
    strategy: '変化先の役職を正しく運用する知識が必要。全役職の立ち回りを習得しておこう。',
    nightAction: true, icon: '\u{2728}', color: '#f0e68c' },
  { name: '新聞配達', team: 'village', rarity: 'V3', ability: '新聞配り',
    description: '毎朝新聞を届ける。新聞配達が生存している間、毎朝「新聞が届きました」と表示される。死亡すると届かなくなる。',
    strategy: 'パン屋と同様の生存確認役職。死亡がバレるため狼の噛み先選択に影響を与える。新聞は毎日設定を忘れないこと。',
    nightAction: false, icon: '\u{1F4F0}', color: '#7ee787' },
  { name: '詩人', team: 'village', rarity: 'V3', ability: '歌の啓示',
    description: '毎朝、前夜に能力を使用した役職からランダムで一人について、誰に能力を使用したかを全体に歌で知らせる。',
    strategy: '自動で情報が公開されるため推理を助ける。ただし狩人の護衛先なども公開される可能性がある点に注意。',
    nightAction: false, icon: '\u{1F3B6}', color: '#79c0ff' },
  { name: 'イタコ', team: 'village', rarity: 'V3', ability: '降霊',
    description: 'ゲーム中に一度だけ、死亡しているプレイヤーを一人選び、その人の役職を知ることができる。',
    strategy: '処刑された人の役職確認で占い師の真偽判定や残り人狼数の特定に活用。タイミングが重要。',
    nightAction: true, icon: '\u{1F47B}', color: '#b392f0' },
  { name: '家政婦', team: 'village', rarity: 'V3', ability: '目撃',
    description: '毎夜一人を訪問し、訪問先が人狼に襲撃されて死亡した場合、人狼のうち一人の正体を目撃する。',
    strategy: '噛まれそうな位置（占い師など）を訪問すると人狼を特定できるチャンスがある。情報量は絶大。',
    nightAction: true, icon: '\u{1F9F9}', color: '#7ee787' },
  { name: 'ギャンブラー', team: 'village', rarity: 'V3', ability: '票蓄積',
    description: '投票時に「投票」か「票をためる」を選択可。ためた票はストック（最大9票）され、投票時に全て使われる。',
    strategy: 'ここぞという場面で大量票を投じて吊り先をコントロール。序盤はためて終盤に一気に使おう。',
    nightAction: false, icon: '\u{1F3B0}', color: '#f0c000' },

  // ===== V3 新役職（人狼陣営） =====
  { name: '心眼の人狼', team: 'werewolf', rarity: 'V3', ability: '心眼',
    description: '特殊な感覚を持つ人狼。投票先の役職を感じ取る情報収集能力を持つ。',
    strategy: '得られた情報を仲間と共有し、効率的に村の重要役職を排除していこう。',
    nightAction: true, icon: '\u{1F440}', color: '#f85149' },
  { name: 'ギャンブル狼', team: 'werewolf', rarity: 'V3', ability: 'ギャンブル襲撃',
    description: '襲撃時にギャンブル要素が加わる人狼。襲撃の成否や追加効果がランダムで変わる。',
    strategy: '運に左右されるが当たれば通常以上の効果。重要場面ではリスク計算を慎重に。',
    nightAction: true, icon: '\u{1F3B2}', color: '#da3633' },
  { name: '人狼王', team: 'werewolf', rarity: 'V3', ability: '王の威厳',
    description: '人狼のリーダー格。処刑されても一度だけ耐えることができる生存能力の高い人狼。',
    strategy: '処刑耐性を活かして大胆に騙りに出ることも可能。能力がバレると集中的に狙われるので注意。',
    nightAction: true, icon: '\u{1F451}', color: '#da3633' },
  { name: '窮地の人狼', team: 'werewolf', rarity: 'V3', ability: '窮地の力',
    description: '追い詰められた状況で真の力を発揮する人狼。仲間の人狼が減るほど強化される。',
    strategy: '序盤は通常の人狼として立ち回り、仲間が減った終盤で強化能力を活かして逆転を狙おう。',
    nightAction: true, icon: '\u{1F630}', color: '#f85149' },
  { name: '黒い占い師', team: 'werewolf', rarity: 'V3', ability: '偽占い',
    description: '人狼陣営の占い師。毎夜一人を占い相手の役職を知ることができるが、村に嘘の占い結果を報告して混乱させる。',
    strategy: '真占いと同じ能力を持つため信用を取りやすい。得た情報で効果的に偽結果を作り出そう。',
    nightAction: true, icon: '\u{1F52E}', color: '#da3633' },
  { name: '誘惑の狼信者', team: 'werewolf', rarity: 'V3', ability: '誘惑',
    description: '人狼を知っている狂人系。特定条件下で市民陣営を誘惑し、判断を狂わせる能力を持つ。',
    strategy: '人狼を知っているため的確に援護できる。誘惑能力で重要役職の行動を妨害しよう。',
    nightAction: true, icon: '\u{1F48B}', color: '#f47067' },
  { name: '封魔の狼信者', team: 'werewolf', rarity: 'V3', ability: '封印',
    description: '人狼を知っている狂人系。対象の能力を一時的に封印し、市民陣営の能力者を無力化できる。',
    strategy: '占い師や狩人の能力を封印すれば襲撃成功率が大幅アップ。封印対象の選択が勝敗を分ける。',
    nightAction: true, icon: '\u{1F512}', color: '#f47067' },
  { name: '女王騙り', team: 'werewolf', rarity: 'V3', ability: '女王偽装',
    description: '女王のふりをする人狼陣営の役職。女王が存在する屋敷で効果を発揮し、村を混乱させる。',
    strategy: '偽女王との関係性を利用して村を混乱させよう。本物の女王がいる屋敷では強力。',
    nightAction: false, icon: '\u{1F3AD}', color: '#f85149' },
  { name: '闇の代身', team: 'werewolf', rarity: 'V3', ability: '身代わり',
    description: '人狼陣営の身代わり役職。仲間の人狼が処刑された場合、代わりに死亡することがある。人狼の生存を助ける。',
    strategy: '人狼の盾となる存在。処刑から仲間を守りつつ、自身の正体を隠して立ち回ろう。',
    nightAction: false, icon: '\u{1F311}', color: '#da3633' },

  // ===== V3 新役職（妖狐陣営） =====
  { name: '饒舌な妖狐', team: 'fox', rarity: 'V3', ability: '饒舌＋襲撃耐性',
    description: '妖狐の能力を持ちつつ、毎日指定されたワードを発言に含めなければならない。含めないと翌朝死亡する。',
    strategy: '人狼に襲撃されても死なないがワード制約がある。自然にワードを織り込む技術が求められる上級者向け。',
    nightAction: false, icon: '\u{1F98A}', color: '#e3b341' },
  { name: 'ささやく背教者', team: 'fox', rarity: 'V3', ability: '狐チャット',
    description: '背徳者の上位互換。妖狐が誰かを知り、さらに妖狐と夜にチャットで会話ができる。妖狐全滅で後追い死。',
    strategy: '妖狐と直接連携できるため戦略を合わせやすい。妖狐を守りつつ援護する立ち回りが基本。',
    nightAction: false, icon: '\u{1F5E3}', color: '#d29922' },

  // ===== 追加・市民陣営 =====
  { name: '騎士', team: 'village', rarity: '特殊', ability: '護衛（連続可）',
    description: '狩人と同じく毎晩一人を護衛できるが、連続して同じ人を護衛できる。',
    strategy: '占い師を連続護衛できるのが最大のメリット。狩人より安定した護衛が可能。',
    nightAction: true, icon: '\u{1F6E1}', color: '#3fb950' },
  /* 巫女は既に登録済み（line 85付近） */
  { name: '探偵', team: 'village', rarity: '特殊', ability: '遺言読み',
    description: '死亡した人の遺言（最後の発言）を読むことができる。',
    strategy: '死者の遺言から有力な情報を得られる。重要な推理材料になることも。',
    nightAction: false, icon: '\u{1F575}', color: '#79c0ff' },
  { name: '罠師', team: 'village', rarity: '特殊', ability: '罠設置',
    description: '毎晩一人に罠を仕掛け、その人を訪れた人狼を殺す。ただし味方の能力者も罠にかかる。',
    strategy: '人狼が噛みそうな位置に罠を張る。占い師護衛先と被らないよう注意。',
    nightAction: true, icon: '\u{1FAA4}', color: '#da3633' },
  { name: '天文学者', team: 'village', rarity: '特殊', ability: '星占い',
    description: '毎晩2人を選び、その2人が同じ陣営かどうかを知ることができる。',
    strategy: '2人の関係性を調べられるため、ライン考察に非常に強い。効率的な占い先選びが鍵。',
    nightAction: true, icon: '\u{1F52D}', color: '#a5d6ff' },
  { name: '狼飼い', team: 'village', rarity: '特殊', ability: '狼化',
    description: '市民陣営だが、処刑されると翌日から人狼として復活する特殊な役職。',
    strategy: '処刑されないように立ち回る。万が一処刑された場合は人狼として勝利を目指すことに。',
    nightAction: false, icon: '\u{1F415}', color: '#8b949e' },
  { name: '預言者', team: 'village', rarity: '特殊', ability: '初日占い結果取得',
    description: '初日の夜に自動的にランダムな一人の占い結果を得る。以降の占い能力はない。',
    strategy: '初日に得た情報を基に推理を進める。1回きりの占い結果を最大限活用しよう。',
    nightAction: false, icon: '\u{1F4DC}', color: '#d2a8ff' },
  { name: '花嫁', team: 'village', rarity: '特殊', ability: '花婿認知',
    description: '花婿が誰かを知ることができる。花婿と協力して村を勝利に導く。',
    strategy: '花婿との連携で白確定ペアを作れる。双子に似た運用が可能。',
    nightAction: false, icon: '\u{1F470}', color: '#f0c0e0' },
  { name: '花婿', team: 'village', rarity: '特殊', ability: '花嫁認知',
    description: '花嫁が誰かを知ることができる。花嫁と協力して村を勝利に導く。',
    strategy: '花嫁との連携で白確定ペアを作れる。双子に似た運用が可能。',
    nightAction: false, icon: '\u{1F935}', color: '#79c0ff' },
  { name: '霊能者の弟子', team: 'village', rarity: '特殊', ability: '霊能継承',
    description: '霊能者が死亡した場合、霊能者の能力を引き継ぐ。',
    strategy: '霊能者が死ぬまでは能力なし。霊能者死亡後にCOして結果を出していく。',
    nightAction: false, icon: '\u{2728}', color: '#79c0ff' },
  { name: '大女優', team: 'village', rarity: '特殊', ability: '演技',
    description: '死亡時に人狼と表示される市民陣営の役職。霊能結果も人狼判定。',
    strategy: '処刑時に人狼判定が出るため、村を混乱させてしまう可能性がある。COタイミングが重要。',
    nightAction: false, icon: '\u{1F3AC}', color: '#f0883e' },
  { name: '絶対人狼', team: 'village', rarity: '特殊', ability: '確定人狼判定',
    description: '占い結果・霊能結果ともに人狼と判定される市民陣営。人狼を騙しやすい。',
    strategy: '人狼から味方と勘違いされる可能性がある。逆手に取って情報を引き出そう。',
    nightAction: false, icon: '\u{1F43A}', color: '#7ee787' },

  // ===== 追加・人狼陣営 =====
  { name: '妖術師', team: 'werewolf', rarity: '特殊', ability: '役職占い',
    description: '人狼陣営の占い師。毎晩一人を選んで役職を知ることができる。人狼が誰かも知っている。',
    strategy: '対抗占い師として偽結果を出しつつ、人狼に役職情報を伝える。狩人や猫又の位置を把握が重要。',
    nightAction: true, icon: '\u{1F9D9}', color: '#f85149' },
  { name: '偽占い師', team: 'werewolf', rarity: '特殊', ability: '偽占い',
    description: '占い結果が常に「人間」と出る偽の占い師。人狼が誰かは知らない。',
    strategy: '真占い師を騙って村を混乱させる。ただし人狼を白判定してしまうリスクもある。',
    nightAction: true, icon: '\u{1F52E}', color: '#da3633' },
  { name: '殺し屋', team: 'werewolf', rarity: '特殊', ability: '暗殺',
    description: '人狼の襲撃とは別に、単独で暗殺を行える人狼陣営の役職。人狼ではないが人狼を知っている。',
    strategy: '人狼の噛みとは別に暗殺できるため、1ターンで2人減らせる。強力だが目立つ。',
    nightAction: true, icon: '\u{1F5E1}', color: '#da3633' },
  { name: '破局の使者', team: 'werewolf', rarity: '特殊', ability: '恋人破壊',
    description: '恋人を見つけて破壊する能力を持つ人狼陣営の役職。',
    strategy: '恋人がいる屋敷で真価を発揮。恋人を排除して人狼陣営の勝利に貢献。',
    nightAction: true, icon: '\u{1F494}', color: '#f85149' },
  { name: '狂人（何者）', team: 'werewolf', rarity: '特殊', ability: '人間判定＋変化',
    description: '処刑で死亡すると何者（霊能結果が不明）になる狂人。',
    strategy: '通常の狂人と同じ立ち回り。死後の霊能結果が不明になるため村を混乱させる。',
    nightAction: false, icon: '\u{2753}', color: '#f47067' },

  // ===== 追加・第三陣営 =====
  { name: '呪狼', team: 'fox', rarity: '特殊', ability: '呪殺無効',
    description: '妖狐の亜種。占い師に占われても呪殺されない特殊な妖狐。',
    strategy: '占われても死なないため、大胆な行動が可能。ただし処刑は有効。',
    nightAction: false, icon: '\u{1F98A}', color: '#e3b341' },
  { name: 'おおかみ男', team: 'other', rarity: '特殊', ability: '襲撃判定',
    description: '第三陣営。人狼に襲撃されると人狼になる。襲撃されなければ市民陣営として扱われる。',
    strategy: '序盤は市民として振る舞い、噛まれたら人狼として立ち回る。どちらの展開にも対応できるよう準備。',
    nightAction: false, icon: '\u{1F43A}', color: '#8b949e' },
  { name: '復讐者', team: 'other', rarity: '特殊', ability: '道連れ指定',
    description: '第三陣営。ゲーム開始時に指定された「復讐対象」を処刑で死亡させれば勝利。',
    strategy: '復讐対象を処刑させるよう誘導する。対象が人狼なら村に協力的に見せかけつつ誘導。',
    nightAction: false, icon: '\u{1F525}', color: '#da3633' },
  { name: 'ハンター', team: 'other', rarity: '特殊', ability: '射殺',
    description: '第三陣営。死亡時に一人を選んで射殺（道連れ）することができる。',
    strategy: '自分が死ぬ際に最も脅威となるプレイヤーを道連れにする。誰を射殺するかの判断力が問われる。',
    nightAction: false, icon: '\u{1F52B}', color: '#f0883e' },
  { name: '覗き魔', team: 'other', rarity: '特殊', ability: '覗き',
    description: '第三陣営。毎晩一人を選んで役職を覗き見することができる。勝利条件は生存。',
    strategy: '情報を得つつ生存を目指す。得た情報をどこまで公開するかが戦略の鍵。',
    nightAction: true, icon: '\u{1F440}', color: '#8b949e' },
  { name: '疫病神', team: 'other', rarity: '特殊', ability: '感染',
    description: '第三陣営。毎晩一人に感染させ、自分が処刑されると感染者全員が死亡する。',
    strategy: '多くの人に感染させてから処刑されるのが理想。ただし噛まれると効果なし。',
    nightAction: true, icon: '\u{1F9A0}', color: '#da3633' },
  { name: '純愛者', team: 'lovers', rarity: '特殊', ability: '恋人指定',
    description: '初日の夜に一人を選んで恋人にする。恋人と2人で生き残れば勝利。片方が死ぬと後追い。',
    strategy: '強い味方を恋人に選び、2人で生き残る立ち回りを目指す。相手を守りつつ行動。',
    nightAction: true, icon: '\u{1F49E}', color: '#db7ff7' },
  { name: 'キューピッド', team: 'lovers', rarity: '特殊', ability: '恋人結成',
    description: '初日の夜に2人を選んで恋人にする。キューピッド自身は恋人に含まれない。村の勝利が自分の勝利。',
    strategy: '市民同士を恋人にするのが安定。人狼を含む恋人にすると村が不利になる可能性。',
    nightAction: true, icon: '\u{1F3F9}', color: '#f0c0e0' },

  // ===== V3追加分の補完 =====
  { name: '人狼見習い', team: 'werewolf', rarity: 'V3', ability: '人狼継承',
    description: 'V3新役職。最初は人狼ではないが、人狼が全滅すると人狼に変化する。人狼を知っている。',
    strategy: '序盤は狂人的に動きつつ、人狼全滅時に備える。人狼が生存中は直接的な攻撃力はない。',
    nightAction: false, icon: '\u{1F43E}', color: '#f85149' },
  { name: '呪い師', team: 'village', rarity: 'V3', ability: '呪い付与',
    description: 'V3新役職。毎晩一人に呪いをかけ、呪われた人が人狼に襲撃されると人狼が死ぬ。',
    strategy: '罠師と似た能力。噛まれそうな位置に呪いをかけて人狼を倒す。',
    nightAction: true, icon: '\u{1F480}', color: '#a78bfa' },
  { name: '守護天使', team: 'village', rarity: 'V3', ability: '永続護衛',
    description: 'V3新役職。初日の夜に一人を選び、その人をゲーム中ずっと護衛し続ける。',
    strategy: '占い師を選べば強力だが、初日に真占い師を見極める必要がある。',
    nightAction: true, icon: '\u{1F47C}', color: '#7ee787' },
  { name: '影武者', team: 'village', rarity: 'V3', ability: '身代わり',
    description: 'V3新役職。特定の役職者が襲撃された際に身代わりで死亡する。',
    strategy: '重要役職を守る盾役。自分の存在を匂わせつつ潜伏するのが基本。',
    nightAction: false, icon: '\u{1F977}', color: '#3fb950' },
  { name: '密偵', team: 'village', rarity: 'V3', ability: '盗聴',
    description: 'V3新役職。人狼の夜チャットの一部を盗み見ることができる。',
    strategy: '人狼の会話から貴重な情報を得られる。得た情報の出し方とタイミングが重要。',
    nightAction: true, icon: '\u{1F576}', color: '#79c0ff' },
  { name: '白魔術師', team: 'village', rarity: 'V3', ability: '蘇生',
    description: 'V3新役職。一度だけ死亡した市民陣営のプレイヤーを蘇生させることができる。',
    strategy: '占い師や狩人など重要役職が死亡した時に蘇生させる。使いどころが勝敗を分ける。',
    nightAction: true, icon: '\u{2728}', color: '#a5d6ff' },
  { name: '結界師', team: 'village', rarity: 'V3', ability: '結界',
    description: 'V3新役職。毎晩一人に結界を張り、あらゆる夜の行動から守る。',
    strategy: '護衛だけでなく占いや呪殺からも守れる。妖狐保護にも使える両刃の剣。',
    nightAction: true, icon: '\u{1F6E1}', color: '#58a6ff' },
  { name: '黒魔術師', team: 'werewolf', rarity: 'V3', ability: '呪殺',
    description: 'V3新役職。人狼陣営の能力者。毎晩一人を呪殺する能力を持つ。',
    strategy: '人狼の襲撃とは別に呪殺できる。占い師や狩人を優先的に狙う。',
    nightAction: true, icon: '\u{1F9D9}', color: '#da3633' },
  { name: '呪狼', team: 'werewolf', rarity: 'V3', ability: '呪い噛み',
    description: 'V3新役職。襲撃した相手を呪い、占い師に占われると呪殺される状態にする人狼。',
    strategy: '白確定の人を噛んで呪い状態にし、占い師が占うと死ぬトラップを仕掛ける。',
    nightAction: true, icon: '\u{1F43A}', color: '#da3633' },
  { name: '影の人狼', team: 'werewolf', rarity: 'V3', ability: '姿隠し',
    description: 'V3新役職。襲撃時に自分の正体を隠せる人狼。襲撃失敗時も正体がバレにくい。',
    strategy: 'GJが出ても狩人に正体がバレにくい。大胆な襲撃先を選べる。',
    nightAction: true, icon: '\u{1F311}', color: '#f85149' },
  { name: '月狐', team: 'fox', rarity: 'V3', ability: '月光占い',
    description: 'V3新役職。妖狐陣営で夜に一人を選んで陣営を知ることができる。',
    strategy: '占い能力を持つ妖狐。人狼の位置を把握して生存戦略に活かす。',
    nightAction: true, icon: '\u{1F319}', color: '#e3b341' },
  // ===== 悪魔陣営 =====
  { name: '悪魔', team: 'devil', rarity: '特殊', ability: '契約',
    description: '悪魔陣営の首領。毎晩一人と「契約」を結び、契約者を悪魔陣営に引き込む。人狼とも市民とも異なる第三勢力。',
    strategy: '序盤は潜伏して信頼を得つつ、要所で契約を結んで陣営を拡大する。占い師に見つかると致命的なため、怪しまれない立ち回りが重要。人狼との共倒れも狙える。',
    nightAction: true, icon: '\u{1F608}', color: '#9333ea' },
  // ===== チキン陣営 =====
  { name: 'チキン', team: 'chicken', rarity: 'V3', ability: '逃走',
    description: 'チキン陣営の唯一の役職。処刑されそうになると「逃走」を試みる。生存していればチキン陣営の勝利。投票で最多票を受けると逃走判定が発生する。',
    strategy: '目立たず生き残ることが目標。積極的に発言して村に貢献しているように見せつつ、吊り先にならないよう立ち回る。最終日まで生存できれば勝利。',
    nightAction: false, icon: '\u{1F414}', color: '#f59e0b' },
  // ===== ネタ枠 =====
  { name: 'グール', team: 'other', rarity: 'ネタ', ability: '死者蘇生',
    description: 'ネタ役職。処刑された翌日に一度だけ蘇生できる。蘇生後は能力を失い普通の村人として行動する。',
    strategy: 'あえて処刑されてから蘇生するという斬新な戦法が可能。蘇生後は情報アドバンテージを活かして推理に貢献する。ネタ枠だが使いこなせれば強力。',
    nightAction: false, icon: '\u{1F9DF}', color: '#6b7280' },
];

// Team display info
const TEAM_INFO = {
  village:  { name: '市民陣営', color: '#7ee787', icon: '&#x1F33F;' },
  werewolf: { name: '人狼陣営', color: '#f85149', icon: '&#x1F43A;' },
  fox:      { name: '妖狐陣営', color: '#d29922', icon: '&#x1F98A;' },
  lovers:   { name: '恋人陣営', color: '#db7ff7', icon: '&#x1F495;' },
  other:    { name: 'その他', color: '#8b949e', icon: '&#x2753;' },
  devil:    { name: '悪魔陣営', color: '#9333ea', icon: '&#x1F608;' },
  chicken:  { name: 'チキン陣営', color: '#f59e0b', icon: '&#x1F414;' },
};
