const ROLES_DATA = [
  // ===== 市民陣営 =====
  { name: '市民', team: 'village', rarity: '基本', ability: 'なし',
    description: '特殊能力を持たない一般市民。議論と投票で人狼を見つけ出す。',
    strategy: '発言の矛盾や行動パターンからスキルで人狼を見抜く。寡黙にならず積極的に議論に参加することが大切。',
    nightAction: false },
  { name: '占い師', team: 'village', rarity: '基本', ability: '占い',
    description: '毎晩一人を選んで占い、人狼かどうかを知ることができる。村の最重要役職。',
    strategy: '初日に即COし、毎日占い結果を報告する。グレーを詰める占いが基本。対抗が出た場合はロラ（ローラー）か真偽判定を行う。',
    nightAction: true },
  { name: '霊能者', team: 'village', rarity: '基本', ability: '霊能',
    description: '処刑された人が人狼だったかどうかを知ることができる。',
    strategy: '占い師の真偽判定に重要。COタイミングは占い師と同日か、対抗が出た場合に。',
    nightAction: false },
  { name: '狩人', team: 'village', rarity: '基本', ability: '護衛',
    description: '毎晩一人を護衛し、人狼の襲撃から守ることができる。連続護衛不可のルールもある。',
    strategy: '占い師の護衛が基本。GJ（護衛成功）が出たら状況に応じてCOも視野に。',
    nightAction: true },
  { name: '猫又', team: 'village', rarity: '特殊', ability: '道連れ',
    description: '処刑された場合、ランダムで一人を道連れにする。人狼に襲撃された場合、襲撃した人狼を道連れにする。',
    strategy: '噛まれた場合は確定で人狼を道連れにできるため、吊られないよう立ち回る。COタイミングが重要。',
    nightAction: false },
  { name: '双子', team: 'village', rarity: '特殊', ability: '相互認知',
    description: '同じ双子同士でお互いを認知できる。確定白として強力。',
    strategy: '片方がCOし、もう片方が白確認することで強力な白確定が作れる。ただしタイミングに注意。',
    nightAction: false },
  { name: '罠師', team: 'village', rarity: '特殊', ability: '罠設置',
    description: '毎晩一人に罠を仕掛けることができる。罠を仕掛けた人を人狼が襲撃すると人狼が死ぬ。',
    strategy: '狩人と似た役割だが、罠にかかった人狼が死ぬのが最大の違い。噛まれそうな位置に罠を張る。',
    nightAction: true },
  { name: '医者', team: 'village', rarity: '特殊', ability: '蘇生',
    description: '毎晩一人を選び、その人が死亡した場合に一定確率で蘇生させることができる。',
    strategy: '重要役職が死亡した場合の保険。蘇生成功率は低いが、成功すれば非常に強力。',
    nightAction: true },
  { name: '暗殺者', team: 'village', rarity: '特殊', ability: '暗殺',
    description: 'ゲーム中一度だけ、指定した人を暗殺できる。',
    strategy: '確定人狼や確定黒位置に使う。使いどころを誤ると村に不利になるため慎重に。',
    nightAction: true },
  { name: 'パン屋', team: 'village', rarity: '特殊', ability: 'パン配り',
    description: '生存している限り毎朝「パンが届きました」と表示される。死亡すると届かなくなる。',
    strategy: '生存確認役職。パンが届かなくなったら噛まれたことが分かる。白アピールに使える。',
    nightAction: false },
  { name: '長老', team: 'village', rarity: '特殊', ability: '2回耐性',
    description: '人狼の襲撃を一度だけ耐えることができる。2回目の襲撃で死亡する。',
    strategy: '噛まれても1回は生存できるため、潜伏して情報を集めやすい。ただし処刑では1回で死ぬ。',
    nightAction: false },
  { name: '巫女', team: 'village', rarity: '特殊', ability: '呪い判定',
    description: '処刑された人が呪われた役職だったかを知ることができる。',
    strategy: '呪われた役職を見抜くことで、村に重要な情報を提供。',
    nightAction: false },
  { name: '賢者', team: 'village', rarity: '特殊', ability: '役職占い',
    description: '毎晩一人を選んで、その人の役職を知ることができる。占い師の上位互換。',
    strategy: '占い師と同様にCOして情報を出していく。役職まで分かるので対抗の真偽判定に強い。',
    nightAction: true },

  // ===== 人狼陣営 =====
  { name: '人狼', team: 'werewolf', rarity: '基本', ability: '襲撃',
    description: '毎晩一人を襲撃できる。人狼同士は互いを認知でき、夜に会話できる。',
    strategy: '市民のふりをして議論をかく乱する。占い師騙りや潜伏など戦術は多彩。仲間との連携が重要。',
    nightAction: true },
  { name: '狂人', team: 'werewolf', rarity: '基本', ability: 'なし（占い白）',
    description: '人狼陣営だが人狼ではないため、占い結果は白（市民）と出る。',
    strategy: '占い師や霊能者を騙って人狼を援護する。人狼が誰かは分からないので、推理して合わせる。',
    nightAction: false },
  { name: '狂信者', team: 'werewolf', rarity: '特殊', ability: '人狼認知',
    description: '狂人の上位互換。人狼が誰か知った状態でゲームが始まる。占い結果は白。',
    strategy: '人狼を知っているので、的確に援護できる。騙り役として非常に強力。',
    nightAction: false },
  { name: 'ささやく狂人', team: 'werewolf', rarity: '特殊', ability: '人狼チャット参加',
    description: '人狼のチャットに参加でき、人狼と会話ができる狂人。',
    strategy: '人狼と直接連携できるため、騙りの整合性を取りやすい。最も強力な狂人系。',
    nightAction: false },
  { name: '黒猫', team: 'werewolf', rarity: '特殊', ability: '処刑道連れ',
    description: '処刑された場合、ランダムで村人陣営から一人を道連れにする。',
    strategy: '積極的に吊られにいくことで村を減らせる。猫又COして吊りを誘う戦術も。',
    nightAction: false },
  { name: '賢狼', team: 'werewolf', rarity: '特殊', ability: '役職看破',
    description: '襲撃した人の役職を知ることができる人狼。',
    strategy: '噛んだ相手の役職がわかるため、情報アドバンテージが大きい。',
    nightAction: true },
  { name: '強欲な人狼', team: 'werewolf', rarity: '特殊', ability: '2人襲撃',
    description: '一度だけ、一晩に二人を襲撃することができる人狼。',
    strategy: '終盤の詰みで使ったり、重要役職を一気に2人噛むなど、タイミングが勝負の鍵。',
    nightAction: true },

  // ===== 妖狐陣営 =====
  { name: '妖狐', team: 'fox', rarity: '特殊', ability: '襲撃耐性',
    description: '人狼に襲撃されても死なない。ただし占い師に占われると死ぬ（呪殺）。勝利条件は生存。',
    strategy: '占われないように目立たず立ち回る。村でも狼でもない第三勢力として、漁夫の利を狙う。',
    nightAction: false },
  { name: '子狐', team: 'fox', rarity: '特殊', ability: '曖昧占い',
    description: '一定確率で占いの結果がわかる（失敗することもある）。占い師に占われると死ぬ。',
    strategy: '不確実だが占い能力を活かして狐陣営の生存を助ける。',
    nightAction: true },
  { name: '背徳者', team: 'fox', rarity: '特殊', ability: '狐認知',
    description: '妖狐が誰かを知った状態でゲーム開始。妖狐が全滅すると後追い死する。',
    strategy: '妖狐の援護役。狂人のように振る舞いつつ、妖狐を守る立ち回りが重要。',
    nightAction: false },

  // ===== 恋人陣営 =====
  { name: '恋人', team: 'lovers', rarity: '特殊', ability: '相互認知・後追い',
    description: '恋人同士はお互いを認知。片方が死ぬともう片方も後追い死する。恋人だけで生存すれば勝利。',
    strategy: '目立たず生存することが最優先。お互いを庇いすぎるとバレるので注意。',
    nightAction: false },
];

// Team display info
const TEAM_INFO = {
  village:  { name: '市民陣営', color: '#7ee787', icon: '&#x1F33F;' },
  werewolf: { name: '人狼陣営', color: '#f85149', icon: '&#x1F43A;' },
  fox:      { name: '妖狐陣営', color: '#d29922', icon: '&#x1F98A;' },
  lovers:   { name: '恋人陣営', color: '#db7ff7', icon: '&#x1F495;' },
};
